settings:
  # Please make sure these are in capitals.
  # You can find the latest list of entity types here, these can only be item frame types.
  # https://javadocs.olziedev.com/spigot/latest/org/bukkit/entity/EntityType.html
  types:
    - "ITEM_FRAME"
    - "GLOW_ITEM_FRAME"

lang:
  hide-frame: "&eSuccessfully &c&lhidden&e the itemframe!"
  show-frame: "&eSuccessfully &a&lshown&e the itemframe!"
  no-permission: "&cYou don't have permission to use this command."
  not-itemframe: "&cYou must be looking at an item frame (within 5 blocks)."
  hide-glow: "&eSuccessfully &c&lhidden&e the glow of the itemframe!"
  show-glow: "&eSuccessfully &a&lshown&e the glow of the itemframe!"
  toggle-off: "&eSuccessfully &c&ldisabled&e the right-click to toggle itemframe visibility!"
  toggle-on: "&eSuccessfully &a&lenabled&e the itemframe the right-click to toggle itemframe visibility!"